### ISSUE TITLE
Malformed certificate causes "Verify LDAP Config" to panic in tanzu CLI

### ISSUE THREAD

**Issue by cormachogan** [vmware-tanzu/community-edition#1772]
## Bug Report

I hit the following issue standing up a new management cluster on vSphere (TCE) Configuring LDAPS via the UI, I added a base64 encoded cert to the cert field by mistake. On launching the Verify LDAP configuration, the following panic is thrown in the CLI:

```
2021/09/16 09:57:36 http: panic serving 127.0.0.1:59761: runtime error: invalid memory address or nil pointer dereference
goroutine 816 [running]:
net/http.(*conn).serve.func1(0xc001229c20)
	/usr/local/go/src/net/http/server.go:1824 +0x153
panic(0x356eba0, 0x57ca230)
	/usr/local/go/src/runtime/panic.go:971 +0x499
github.com/go-ldap/ldap/v3.(*Conn).nextMessageID(...)
	/go/pkg/mod/github.com/go-ldap/ldap/v3@v3.3.0/conn.go:283
github.com/go-ldap/ldap/v3.(*Conn).doRequest(0x0, 0x409dbe0, 0xc000e9a580, 0x40, 0x40, 0x382d9a0)
	/go/pkg/mod/github.com/go-ldap/ldap/v3@v3.3.0/request.go:26 +0x61
github.com/go-ldap/ldap/v3.(*Conn).SimpleBind(0x0, 0xc000e9a580, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/go-ldap/ldap/v3@v3.3.0/bind.go:65 +0x99
github.com/go-ldap/ldap/v3.(*Conn).Bind(...)
	/go/pkg/mod/github.com/go-ldap/ldap/v3@v3.3.0/bind.go:104
github.com/vmware-tanzu/tanzu-framework/pkg/v1/tkg/ldap.(*client).LdapBind(0xc00196a460, 0xe01, 0x0, 0x0)
	/tmp/tce-release/tanzu-framework/pkg/v1/tkg/ldap/client.go:88 +0x10f
github.com/vmware-tanzu/tanzu-framework/pkg/v1/tkg/web/server/handlers.(*App).VerifyLdapBind(0xc00031ce00, 0xc000acd000, 0x0, 0xc000ea8730)
	/tmp/tce-release/tanzu-framework/pkg/v1/tkg/web/server/handlers/ldap.go:32 +0x58
github.com/vmware-tanzu/tanzu-framework/pkg/v1/tkg/web/server/restapi/operations/ldap.VerifyLdapBindHandlerFunc.Handle(0xc000e3bf40, 0xc000acd000, 0xc000accf00, 0x409ff60)
	/tmp/tce-release/tanzu-framework/pkg/v1/tkg/web/server/restapi/operations/ldap/verify_ldap_bind.go:19 +0x30
github.com/vmware-tanzu/tanzu-framework/pkg/v1/tkg/web/server/restapi/operations/ldap.(*VerifyLdapBind).ServeHTTP(0xc0010d04c8, 0x40e64a8, 0xc000c92380, 0xc000acd000)
	/tmp/tce-release/tanzu-framework/pkg/v1/tkg/web/server/restapi/operations/ldap/verify_ldap_bind.go:54 +0x16c
github.com/go-openapi/runtime/middleware.NewOperationExecutor.func1(0x40e64a8, 0xc000c92380, 0xc000acd000)
	/go/pkg/mod/github.com/go-openapi/runtime@v0.19.4/middleware/operation.go:28 +0x75
net/http.HandlerFunc.ServeHTTP(0xc000597da0, 0x40e64a8, 0xc000c92380, 0xc000acd000)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/vmware-tanzu/tanzu-framework/pkg/v1/tkg/web/server.FileServerMiddleware.func1(0x40e64a8, 0xc000c92380, 0xc000acd000)
	/tmp/tce-release/tanzu-framework/pkg/v1/tkg/web/server/serve.go:99 +0x14d
net/http.HandlerFunc.ServeHTTP(0xc000cb2390, 0x40e64a8, 0xc000c92380, 0xc000acd000)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/go-openapi/runtime/middleware.NewRouter.func1(0x40e64a8, 0xc000c92380, 0xc000acce00)
	/go/pkg/mod/github.com/go-openapi/runtime@v0.19.4/middleware/router.go:76 +0x359
net/http.HandlerFunc.ServeHTTP(0xc00084aec0, 0x40e64a8, 0xc000c92380, 0xc000acce00)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/go-openapi/runtime/middleware.Redoc.func1(0x40e64a8, 0xc000c92380, 0xc000acce00)
	/go/pkg/mod/github.com/go-openapi/runtime@v0.19.4/middleware/redoc.go:72 +0x293
net/http.HandlerFunc.ServeHTTP(0xc0008289c0, 0x40e64a8, 0xc000c92380, 0xc000acce00)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/go-openapi/runtime/middleware.Spec.func1(0x40e64a8, 0xc000c92380, 0xc000acce00)
	/go/pkg/mod/github.com/go-openapi/runtime@v0.19.4/middleware/spec.go:46 +0x1a3
net/http.HandlerFunc.ServeHTTP(0xc000828a00, 0x40e64a8, 0xc000c92380, 0xc000acce00)
	/usr/local/go/src/net/http/server.go:2069 +0x44
net/http.serverHandler.ServeHTTP(0xc000648540, 0x40e64a8, 0xc000c92380, 0xc000acce00)
	/usr/local/go/src/net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc001229c20, 0x40edb70, 0xc000e9a4c0)
	/usr/local/go/src/net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3013 +0x39b
2021/09/16 09:57:37 http: panic serving 127.0.0.1:59762: runtime error: invalid memory address or nil pointer dereference
goroutine 779 [running]:
net/http.(*conn).serve.func1(0xc0013a4320)
	/usr/local/go/src/net/http/server.go:1824 +0x153
panic(0x356eba0, 0x57ca230)
	/usr/local/go/src/runtime/panic.go:971 +0x499
github.com/go-ldap/ldap/v3.(*Conn).nextMessageID(...)
	/go/pkg/mod/github.com/go-ldap/ldap/v3@v3.3.0/conn.go:283
github.com/go-ldap/ldap/v3.(*Conn).doRequest(0x0, 0x409dbc0, 0xc00109ea80, 0xc0005ed448, 0x203000, 0x4e)
	/go/pkg/mod/github.com/go-ldap/ldap/v3@v3.3.0/request.go:26 +0x61
github.com/go-ldap/ldap/v3.(*Conn).Search(0x0, 0xc00109ea80, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/go-ldap/ldap/v3@v3.3.0/search.go:360 +0x8b
github.com/vmware-tanzu/tanzu-framework/pkg/v1/tkg/ldap.(*client).LdapUserSearch(0xc00196a460, 0xe01, 0x0, 0x0)
	/tmp/tce-release/tanzu-framework/pkg/v1/tkg/ldap/client.go:133 +0x2af
github.com/vmware-tanzu/tanzu-framework/pkg/v1/tkg/web/server/handlers.(*App).VerifyUserSearch(0xc00031ce00, 0xc0006f2500, 0x0, 0xc000ea8730)
	/tmp/tce-release/tanzu-framework/pkg/v1/tkg/web/server/handlers/ldap.go:46 +0x58
github.com/vmware-tanzu/tanzu-framework/pkg/v1/tkg/web/server/restapi/operations/ldap.VerifyLdapUserSearchHandlerFunc.Handle(0xc000e3bf50, 0xc0006f2500, 0xc0006f2400, 0x40a01a0)
	/tmp/tce-release/tanzu-framework/pkg/v1/tkg/web/server/restapi/operations/ldap/verify_ldap_user_search.go:19 +0x30
github.com/vmware-tanzu/tanzu-framework/pkg/v1/tkg/web/server/restapi/operations/ldap.(*VerifyLdapUserSearch).ServeHTTP(0xc0010d0528, 0x40e64a8, 0xc000d08460, 0xc0006f2500)
	/tmp/tce-release/tanzu-framework/pkg/v1/tkg/web/server/restapi/operations/ldap/verify_ldap_user_search.go:54 +0x16c
github.com/go-openapi/runtime/middleware.NewOperationExecutor.func1(0x40e64a8, 0xc000d08460, 0xc0006f2500)
	/go/pkg/mod/github.com/go-openapi/runtime@v0.19.4/middleware/operation.go:28 +0x75
net/http.HandlerFunc.ServeHTTP(0xc000597da0, 0x40e64a8, 0xc000d08460, 0xc0006f2500)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/vmware-tanzu/tanzu-framework/pkg/v1/tkg/web/server.FileServerMiddleware.func1(0x40e64a8, 0xc000d08460, 0xc0006f2500)
	/tmp/tce-release/tanzu-framework/pkg/v1/tkg/web/server/serve.go:99 +0x14d
net/http.HandlerFunc.ServeHTTP(0xc000cb2390, 0x40e64a8, 0xc000d08460, 0xc0006f2500)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/go-openapi/runtime/middleware.NewRouter.func1(0x40e64a8, 0xc000d08460, 0xc000acd100)
	/go/pkg/mod/github.com/go-openapi/runtime@v0.19.4/middleware/router.go:76 +0x359
net/http.HandlerFunc.ServeHTTP(0xc00084aec0, 0x40e64a8, 0xc000d08460, 0xc000acd100)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/go-openapi/runtime/middleware.Redoc.func1(0x40e64a8, 0xc000d08460, 0xc000acd100)
	/go/pkg/mod/github.com/go-openapi/runtime@v0.19.4/middleware/redoc.go:72 +0x293
net/http.HandlerFunc.ServeHTTP(0xc0008289c0, 0x40e64a8, 0xc000d08460, 0xc000acd100)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/go-openapi/runtime/middleware.Spec.func1(0x40e64a8, 0xc000d08460, 0xc000acd100)
	/go/pkg/mod/github.com/go-openapi/runtime@v0.19.4/middleware/spec.go:46 +0x1a3
net/http.HandlerFunc.ServeHTTP(0xc000828a00, 0x40e64a8, 0xc000d08460, 0xc000acd100)
	/usr/local/go/src/net/http/server.go:2069 +0x44
net/http.serverHandler.ServeHTTP(0xc000648540, 0x40e64a8, 0xc000d08460, 0xc000acd100)
	/usr/local/go/src/net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc0013a4320, 0x40edb70, 0xc000e9a5c0)
	/usr/local/go/src/net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3013 +0x39b
2021/09/16 09:57:37 http: panic serving 127.0.0.1:59763: runtime error: invalid memory address or nil pointer dereference
goroutine 780 [running]:
net/http.(*conn).serve.func1(0xc0013a43c0)
	/usr/local/go/src/net/http/server.go:1824 +0x153
panic(0x356eba0, 0x57ca230)
	/usr/local/go/src/runtime/panic.go:971 +0x499
github.com/go-ldap/ldap/v3.(*Conn).nextMessageID(...)
	/go/pkg/mod/github.com/go-ldap/ldap/v3@v3.3.0/conn.go:283
github.com/go-ldap/ldap/v3.(*Conn).doRequest(0x0, 0x409dbc0, 0xc0016f0480, 0xc000eae420, 0x203000, 0x25)
	/go/pkg/mod/github.com/go-ldap/ldap/v3@v3.3.0/request.go:26 +0x61
github.com/go-ldap/ldap/v3.(*Conn).Search(0x0, 0xc0016f0480, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/go-ldap/ldap/v3@v3.3.0/search.go:360 +0x8b
github.com/vmware-tanzu/tanzu-framework/pkg/v1/tkg/ldap.(*client).LdapGroupSearch(0xc00196a460, 0xe01, 0x0, 0x0)
	/tmp/tce-release/tanzu-framework/pkg/v1/tkg/ldap/client.go:192 +0x2fe
github.com/vmware-tanzu/tanzu-framework/pkg/v1/tkg/web/server/handlers.(*App).VerifyGroupSearch(0xc00031ce00, 0xc0001bfa00, 0x0, 0xc000eae730)
	/tmp/tce-release/tanzu-framework/pkg/v1/tkg/web/server/handlers/ldap.go:60 +0x58
github.com/vmware-tanzu/tanzu-framework/pkg/v1/tkg/web/server/restapi/operations/ldap.VerifyLdapGroupSearchHandlerFunc.Handle(0xc000e3bf60, 0xc0001bfa00, 0xc0001bf900, 0x40a0100)
	/tmp/tce-release/tanzu-framework/pkg/v1/tkg/web/server/restapi/operations/ldap/verify_ldap_group_search.go:19 +0x30
github.com/vmware-tanzu/tanzu-framework/pkg/v1/tkg/web/server/restapi/operations/ldap.(*VerifyLdapGroupSearch).ServeHTTP(0xc0010d0510, 0x40e64a8, 0xc000ac01c0, 0xc0001bfa00)
	/tmp/tce-release/tanzu-framework/pkg/v1/tkg/web/server/restapi/operations/ldap/verify_ldap_group_search.go:54 +0x16c
github.com/go-openapi/runtime/middleware.NewOperationExecutor.func1(0x40e64a8, 0xc000ac01c0, 0xc0001bfa00)
	/go/pkg/mod/github.com/go-openapi/runtime@v0.19.4/middleware/operation.go:28 +0x75
net/http.HandlerFunc.ServeHTTP(0xc000597da0, 0x40e64a8, 0xc000ac01c0, 0xc0001bfa00)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/vmware-tanzu/tanzu-framework/pkg/v1/tkg/web/server.FileServerMiddleware.func1(0x40e64a8, 0xc000ac01c0, 0xc0001bfa00)
	/tmp/tce-release/tanzu-framework/pkg/v1/tkg/web/server/serve.go:99 +0x14d
net/http.HandlerFunc.ServeHTTP(0xc000cb2390, 0x40e64a8, 0xc000ac01c0, 0xc0001bfa00)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/go-openapi/runtime/middleware.NewRouter.func1(0x40e64a8, 0xc000ac01c0, 0xc0001bf800)
	/go/pkg/mod/github.com/go-openapi/runtime@v0.19.4/middleware/router.go:76 +0x359
net/http.HandlerFunc.ServeHTTP(0xc00084aec0, 0x40e64a8, 0xc000ac01c0, 0xc0001bf800)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/go-openapi/runtime/middleware.Redoc.func1(0x40e64a8, 0xc000ac01c0, 0xc0001bf800)
	/go/pkg/mod/github.com/go-openapi/runtime@v0.19.4/middleware/redoc.go:72 +0x293
net/http.HandlerFunc.ServeHTTP(0xc0008289c0, 0x40e64a8, 0xc000ac01c0, 0xc0001bf800)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/go-openapi/runtime/middleware.Spec.func1(0x40e64a8, 0xc000ac01c0, 0xc0001bf800)
	/go/pkg/mod/github.com/go-openapi/runtime@v0.19.4/middleware/spec.go:46 +0x1a3
net/http.HandlerFunc.ServeHTTP(0xc000828a00, 0x40e64a8, 0xc000ac01c0, 0xc0001bf800)
	/usr/local/go/src/net/http/server.go:2069 +0x44
net/http.serverHandler.ServeHTTP(0xc000648540, 0x40e64a8, 0xc000ac01c0, 0xc0001bf800)
	/usr/local/go/src/net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc0013a43c0, 0x40edb70, 0xc00066e180)
	/usr/local/go/src/net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3013 +0x39b
```

UI report is fine, we just need to catch the panic/error thrown by tanzu CLI. Here is the UI output:

![Verify LDAP Config](https://user-images.githubusercontent.com/18258500/133584324-6025285a-a1d1-44b2-ae98-4338fc3fc6e8.png)

## Expected Behavior

No errors should be thrown by the tanzu CLI, even if the cert is malformed.

## Steps to Reproduce the Bug

Management cluster deployment on vSphere through UI. Populate LDAP fields but add an incorrect cert format to cert field. Run the Verify LDAP configuration.

## Environment Details

* Build version (`tanzu version`): 
TCE v0.8.0-rc2
version: v0.2.1
buildDate: 2021-09-13
sha: ceaa474
* Operating System (client):
macOS (big sur) v11.5.2
vSphere 7.0U2c

**Comment by jpmcb** [comment]
I've opened an issue in `tanzu-framework` to track this issue:

- [ ] https://github.com/vmware-tanzu/tanzu-framework/issues/839

We'll keep this open to track the issue in TCE
